version: '3'

services:
  postgresql:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - magnitogorsk

  backend:
    build: CnC_Server
    env_file:
      - .env
    networks:
      - magnitogorsk
    ports: 
      - "4001:80"

networks:
  magnitogorsk:

volumes:
  db_data:
